# Generated by Django 6.0.5 on 2026-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='age',
            field=models.IntegerField(),
        ),
    ]
