# Generated by Django 6.0.5 on 2026-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
