# Generated by Django 6.0.5 on 2026-05-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Respondents',
            new_name='Respondent',
        ),
    ]
