# Generated by Django 6.0.5 on 2026-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_respondent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TXT', 'Text Answer')], max_length=3, null=True),
        ),
    ]
