# Generated by Django 6.0.5 on 2026-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TXT', 'Text Answer'), ('NC', 'Number Choice')], max_length=3, null=True),
        ),
    ]
