# Generated by Django 6.0.5 on 2026-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_remove_personalinfo_birthdate_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
