# Generated by Django 6.0.5 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_personalinfo_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalInfo',
            new_name='Voter',
        ),
    ]
